### ISSUE TITLE
Provide more information how to setup a project

### ISSUE THREAD

**Issue by dhaeb** [xojo/XojoUnit#12]
Hey,
I'm relatively new to Xojo and therefore things are taking it's time and making trouble. I was able to build / run your code. The problem arises when I want to include your test framework in my (external) Console application project - the documentation says "that I should copy the module which I need" into my folder. Well then your core library is not available anymore and I have to reference it externally. 
I would really enjoy to understand how to embed your project into ANY Xojo application - and It would be great if there were more helpful documentation. Can you give a more detailed description, please? 
Thanks for your work anyways! 

Best,

Dan

**Comment by paullefebvre** [comment]
This short video shows the steps (for a desktop project) to quickly set up XojoUnit. The steps are similar for a console project.

https://youtu.be/cOT84No3Ew0

**Comment by dhaeb** [comment]
Thanks for the quick help! I guess this description will do it. I reopen If I have more questions.
