### ISSUE TITLE
API v2

### ISSUE THREAD

**Issue by antoine2711** [xojo/XojoUnit#17]
Hi,

   I converted my project with XojoUnit to a Project APIv2.
Now, I have a lot of problems.

   Do you think you will do a new version for APIv2?

   I have Xojo v2023 r4.

Regards,
   Antoine

**Comment by ws7m** [comment]
Would like API V2 as well.  Not usable really until then.

**Comment by ktekinay** [comment]
Please see the API2 branch updated today and let me know if if you have any issues.

**Comment by ws7m** [comment]
I downloaded the API2 branch and it builds ok, but the run tests buttons are grayed out and do not ever enable.

This was the same behavior I saw when I tried to convert the APIV1 to v2 myself.

**Comment by ws7m** [comment]
If I put my own calls in to run tests and stop tests they all seem to work.

**Comment by ktekinay** [comment]
Which platform, OS, Xojo version, hardware, etc.?

**Comment by ws7m** [comment]
Sorry, API2, Latest version Xojo, Mac OS, MacBookPro M3Max, OS Sonoma

**Comment by ktekinay** [comment]
I am running the same environment and cannot reproduce this in either the IDE or a built app. Is there something else on your system that can be responsible or contributing to this?

**Comment by ws7m** [comment]
Nothing really special.  I have Dropbox, Snagit, Keyboard Maestro, Alfred running.  But none of those are really active when running the unit test.

Debugging, the opening event fires and it enables the run button, disables the stop button.

A breakpoint in the pressed event never fires when clicking on run tests.  AND even after the opening event, the run tests looks grayed out.

Xojo 2024 Release 1.1

As I said above, I can add standard buttons that work just fine to run the tests.  But there is something funky with the tool bar.

**Comment by paullefebvre** [comment]
I also have mostly the same setup and do not have an issue with the toolbar buttons. However, you do need to click on the empty area above the button (where the icon would be) and not on the button text itself. But that is standard behavior for Xojo's toolbar buttons in general.

**Comment by ktekinay** [comment]
Can you post a video, or even a screenshot, of what you're seeing?

**Comment by ws7m** [comment]
Ok so Paul answered it.  It works if I click above the text.  So problem resolved.   But I have to say that is just plain silly behavior on the part of toolbar buttons.  I typically do not use this in my apps so did not realize that was their behavior.

**Comment by antoine2711** [comment]
@ktekinay : thanks a lot. I will try it later.

Regards, Antoine
